apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: repository 
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: ${IMAGE_REPOSITORY}/repository
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: repository 
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/repository.yaml
